#!/usr/bin/env python3
"""
Timing Data Analysis Script
Analyzes pickle files generated by local_cam_with_timing.py
"""

import pickle
import os
import sys
from datetime import datetime
import statistics

def load_timing_data(pickle_file):
    """Load timing data from pickle file"""
    try:
        with open(pickle_file, 'rb') as f:
            data = pickle.load(f)
        print(f"✅ Loaded {len(data)} timing entries from {pickle_file}")
        return data
    except Exception as e:
        print(f"❌ Error loading {pickle_file}: {e}")
        return None

def analyze_timing_data(data):
    """Analyze timing data and generate comprehensive report"""
    
    if not data:
        print("No data to analyze")
        return
    
    print("\n" + "=" * 80)
    print("LATENCY ANALYSIS REPORT")
    print("=" * 80)
    
    # Group by operation type
    operations = {}
    for entry in data:
        op = entry['operation']
        if op not in operations:
            operations[op] = {
                'durations': [],
                'timestamps': [],
                'metadata': []
            }
        operations[op]['durations'].append(entry['duration_ms'])
        operations[op]['timestamps'].append(entry['timestamp'])
        if 'metadata' in entry:
            operations[op]['metadata'].append(entry['metadata'])
    
    # Calculate statistics for each operation
    print("\n📊 OPERATION STATISTICS\n")
    print(f"{'Operation':<35} {'Count':>8} {'Avg(ms)':>10} {'Min(ms)':>10} {'Max(ms)':>10} {'StdDev':>10}")
    print("-" * 95)
    
    operation_stats = {}
    for op in sorted(operations.keys()):
        durations = operations[op]['durations']
        count = len(durations)
        avg = statistics.mean(durations)
        min_val = min(durations)
        max_val = max(durations)
        stddev = statistics.stdev(durations) if count > 1 else 0
        
        operation_stats[op] = {
            'count': count,
            'avg': avg,
            'min': min_val,
            'max': max_val,
            'stddev': stddev
        }
        
        print(f"{op:<35} {count:>8} {avg:>10.2f} {min_val:>10.2f} {max_val:>10.2f} {stddev:>10.2f}")
    
    # Identify bottlenecks
    print("\n🔴 TOP LATENCY BOTTLENECKS\n")
    sorted_by_avg = sorted(operation_stats.items(), key=lambda x: x[1]['avg'], reverse=True)
    
    for i, (op, stats) in enumerate(sorted_by_avg[:10], 1):
        print(f"{i:2}. {op:<35} Avg: {stats['avg']:>8.2f}ms (Max: {stats['max']:>8.2f}ms)")
    
    # Calculate percentiles for key operations
    print("\n📈 PERCENTILE ANALYSIS (Key Operations)\n")
    key_operations = [
        'yolo_inference',
        'claude_api_call',
        'audio_generation_total',
        'frame_processing_total',
        'prepare_frames',
        'process_detections'
    ]
    
    for op in key_operations:
        if op in operations:
            durations = sorted(operations[op]['durations'])
            n = len(durations)
            
            p50 = durations[int(n * 0.5)] if n > 0 else 0
            p90 = durations[int(n * 0.9)] if n > 0 else 0
            p95 = durations[int(n * 0.95)] if n > 0 else 0
            p99 = durations[int(n * 0.99)] if n > 0 else 0
            
            print(f"{op}:")
            print(f"  P50: {p50:>8.2f}ms | P90: {p90:>8.2f}ms | P95: {p95:>8.2f}ms | P99: {p99:>8.2f}ms")
    
    # Analyze frame processing pipeline
    print("\n⚡ FRAME PROCESSING PIPELINE ANALYSIS\n")
    
    pipeline_ops = [
        'wait_for_frames',
        'prepare_frames',
        'yolo_inference',
        'process_detections',
        'frame_composition',
        'video_write'
    ]
    
    total_pipeline = 0
    for op in pipeline_ops:
        if op in operation_stats:
            avg = operation_stats[op]['avg']
            total_pipeline += avg
            print(f"  {op:<30} {avg:>8.2f}ms")
    
    print(f"  {'─' * 30} {'─' * 10}")
    print(f"  {'Total Pipeline Time':<30} {total_pipeline:>8.2f}ms")
    
    # API call analysis
    if 'claude_api_call' in operations:
        print("\n🤖 CLAUDE API ANALYSIS\n")
        api_durations = operations['claude_api_call']['durations']
        print(f"  Total API calls: {len(api_durations)}")
        print(f"  Average latency: {statistics.mean(api_durations):.2f}ms")
        print(f"  Min latency: {min(api_durations):.2f}ms")
        print(f"  Max latency: {max(api_durations):.2f}ms")
        
        # Check if we have metadata about label lengths
        if operations['claude_api_call']['metadata']:
            metadata = operations['claude_api_call']['metadata']
            label_lengths = [m.get('label_length', 0) for m in metadata if 'label_length' in m]
            if label_lengths:
                print(f"  Avg input length: {statistics.mean(label_lengths):.0f} chars")
    
    # Audio processing analysis
    audio_ops = ['audio_generation_total', 'gtts_generation', 'audio_playback', 'audio_cleanup']
    if any(op in operations for op in audio_ops):
        print("\n🔊 AUDIO PROCESSING ANALYSIS\n")
        for op in audio_ops:
            if op in operation_stats:
                stats = operation_stats[op]
                print(f"  {op:<30} Avg: {stats['avg']:>8.2f}ms (Count: {stats['count']})")
    
    # Recommendations
    print("\n💡 RECOMMENDATIONS\n")
    
    # Check for slow operations
    if 'claude_api_call' in operation_stats:
        if operation_stats['claude_api_call']['avg'] > 1000:
            print("  ⚠️  Claude API calls are slow (>1s). Consider:")
            print("      - Reducing prompt size")
            print("      - Batch processing frames")
            print("      - Using a faster model")
    
    if 'yolo_inference' in operation_stats:
        if operation_stats['yolo_inference']['avg'] > 100:
            print("  ⚠️  YOLO inference is slow (>100ms). Consider:")
            print("      - Using YOLOv8n (nano) model")
            print("      - Reducing input resolution")
            print("      - Using GPU acceleration")
    
    if 'audio_generation_total' in operation_stats:
        if operation_stats['audio_generation_total']['avg'] > 500:
            print("  ⚠️  Audio generation is slow (>500ms). Consider:")
            print("      - Pre-generating common phrases")
            print("      - Using faster TTS engine")
            print("      - Caching audio files")
    
    # Check frame rate
    if total_pipeline > 0:
        theoretical_fps = 1000 / total_pipeline
        print(f"\n  📹 Theoretical max FPS: {theoretical_fps:.1f} fps")
        if theoretical_fps < 15:
            print("      ⚠️  Pipeline too slow for real-time (target: 15-30 fps)")
    
    print("\n" + "=" * 80)

def compare_runs(pickle_files):
    """Compare multiple timing data files"""
    print("\n" + "=" * 80)
    print("COMPARING MULTIPLE RUNS")
    print("=" * 80 + "\n")
    
    all_data = {}
    for pfile in pickle_files:
        data = load_timing_data(pfile)
        if data:
            run_name = os.path.basename(pfile)
            all_data[run_name] = data
    
    if len(all_data) < 2:
        print("Need at least 2 runs to compare")
        return
    
    # Extract operation averages for each run
    run_stats = {}
    for run_name, data in all_data.items():
        operations = {}
        for entry in data:
            op = entry['operation']
            if op not in operations:
                operations[op] = []
            operations[op].append(entry['duration_ms'])
        
        run_stats[run_name] = {op: statistics.mean(durations) 
                                for op, durations in operations.items()}
    
    # Compare key operations
    key_ops = ['yolo_inference', 'claude_api_call', 'frame_processing_total']
    
    print(f"{'Operation':<30}", end='')
    for run_name in run_stats.keys():
        print(f"{run_name[:20]:>20}", end='')
    print()
    print("-" * (30 + 20 * len(run_stats)))
    
    for op in key_ops:
        print(f"{op:<30}", end='')
        for run_name, stats in run_stats.items():
            if op in stats:
                print(f"{stats[op]:>18.2f}ms", end='')
            else:
                print(f"{'N/A':>20}", end='')
        print()

def main():
    if len(sys.argv) < 2:
        print("Usage: python analyze_timing.py <pickle_file> [additional_pickle_files...]")
        print("\nExample: python analyze_timing.py timing_data/timing_data_20240101_120000.pkl")
        
        # Try to find pickle files automatically
        pickle_dir = "/home/halab2/buzz_shared/timing_data"
        if os.path.exists(pickle_dir):
            pickle_files = [os.path.join(pickle_dir, f) for f in os.listdir(pickle_dir) 
                           if f.endswith('.pkl')]
            if pickle_files:
                print(f"\nFound {len(pickle_files)} pickle file(s) in {pickle_dir}:")
                for pf in sorted(pickle_files)[-5:]:  # Show last 5
                    print(f"  {pf}")
                print("\nAnalyzing most recent file...")
                sys.argv.append(sorted(pickle_files)[-1])
            else:
                sys.exit(1)
        else:
            sys.exit(1)
    
    pickle_files = sys.argv[1:]
    
    # Analyze first file in detail
    data = load_timing_data(pickle_files[0])
    if data:
        analyze_timing_data(data)
    
    # Compare multiple files if provided
    if len(pickle_files) > 1:
        compare_runs(pickle_files)

if __name__ == "__main__":
    main()
